# React Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: tashwinsj/page 
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: NodePort              
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100         
